### ISSUE TITLE
Unit tests and CI

### ISSUE THREAD

**Issue by dacb** [Neighborhood-Traffic-Flow/neighborhoodtrafficflow#2]
I only saw one unit test.  Flesh out the unit tests, please.  Also, continuous integration seems to be broken or not setup properly.  I do see the CI yml, but I can't find the build logs on travis.

**Comment by kels271828** [comment]
Can you point me to a repo where the CI is working properly so I can see how it should be on ours? From my end I can see all of the build logs on travis, etc.

**Comment by dacb** [comment]
I clicked on the travis badge and it didn't redirect to the travis site so maybe that is a separate formatting issue.

This is the template repo I use for doing a new travis setup: https://github.com/dacb/codebase

**Comment by kels271828** [comment]
I think it's fixed now; we hadn't updated the badges after renaming the repository.
